### ISSUE TITLE
WMS connection error. MapServer not built with WMS Client support, unable to render layer

### ISSUE THREAD

**Issue by Toilal** [camptocamp/docker-mapserver#14]
I'm using this image since months with the same configuration, but after updating the image to latest version, it seems `CONNECTIONTYPE WMS` doesn't work anymore. 

I saw you migrate to a build from scratch, which is really a good idea for a Docker image, but it seems there are some features missing though.

Here's the error

```
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException>
msDrawMap(): WMS connection error. MapServer not built with WMS Client support, unable to render layer &#39;refign&#39;.
</ServiceException>
</ServiceExceptionReport>
```

Also, I think the default tag on Docker hub should point on a stable release (7) instead of master.

**Comment by Toilal** [comment]
mapserver should be compiled with ` –with-wmsclient` flag, which requires some more dependencies.

See http://mapserver.org/id/ogc/wms_client.html#compilation-installation for more information.

**Comment by pvalsecc** [comment]
I've added a few features.

If you use latest for docker images, you should not be surprized if you end up with somthing out of a master branch, IMHO.

If you want a stable version, pick 7 or 7.0 if you want to be sure you don't endup with a non backward compatible 7.2, one day.

**Comment by Toilal** [comment]
Thank you for fixing this and uploading on docker hub so fast, it solved my problem. I'll use 7.0 tag, no problem.
