### ISSUE TITLE
activate ogc api support on master version

### ISSUE THREAD

**Issue by pvgenuchten** [camptocamp/docker-mapserver#252]
mapserver 8 will have ogc api support, would be interesting to already play with it on the master docker

these build parameters seem required to enable it

-DUSE_WFS_SVR
-DUSE_OGCAPI_SVR

See https://mapserver.org/development/rfc/ms-rfc-134.html

mapfile should be loaded as environment param, eg. https://localhost/MS_MAPFILE/ogcapi/collections

**Comment by sbrunner** [comment]
Thanks, I will have a look :-)

**Comment by pvgenuchten** [comment]
I have built the docker with that build option, and activated on the map file (“oga_enable_request” “OGCAPI”), but only get error 500’s so far…

**Comment by sbrunner** [comment]
initial work: #256

**Comment by pvgenuchten** [comment]
hi @sbrunner thanx for the work, i'm trying the v8 but can't get it to work yet
i'm a bit stuck with the scriptalias and how to get it to work with what mapserver expects, on https://mapserver.org/ogc/ogc_api.html it is mentioned that a map-alias should be created, which is then referenced in the url as /cgi-bin/mapserv/{alias}/ogcapi/.... this conflicts with the c2c image where the scriptalias routes any path to the mapserver_wrapper

were you successfull in your experiments? Some docs/guidance on how to improve this would be helpfull

**Comment by pvgenuchten** [comment]
thanks @maltaesousa, that aspect seemed relevant

I have now ogcapi running locally, some guidance:

- enable the mapserver config file for example at /etc/mapserver.conf
- enable and verify OGCAPI_HTML_TEMPLATE_DIRECTORY "/usr/local/share/mapserver/ogcapi/templates/html-bootstrap4/" (there is a typo in the path)
- add a [maps section](https://mapserver.org/ogc/ogc_api.html#configure-the-mapserver-config-file)
   ```
     MAPS
        "example" "/usr/local/share/mapserver/mapserver.map"
     END
   ```
- add (or mount) a mapfile at that location
- in that mapfile add
   ```
           "oga_onlineresource"               "http://127.0.0.1/example/ogcapi"
           "oga_enable_request"               "*"   
   ```
- access the service at http://127.0.0.1/example/ogcapi

**Comment by pvgenuchten** [comment]
thanx all, this works quite nicely now!
