### ISSUE TITLE
Why is "latest" tag not updated?

### ISSUE THREAD

**Issue by cgodkin** [camptocamp/docker-mapserver#254]
Hi CampToCamp maintainers,

Sorry if this is the wrong place to ask this question but I don't know how else.

The "latest" tag on https://hub.docker.com/r/camptocamp/mapserver/tags is 2 years old but there are plenty of newer images there.  

The Docker image "latest" works fine for my purposes but I am just puzzled.  Are the new images unstable or experiments or what?  I just like to stay up to date.  

Thanks for providing the image!

**Comment by sbrunner** [comment]
Just fixed :-)

**Comment by cgodkin** [comment]
Thank you very much.  Works fine!
