### ISSUE TITLE
Add docker image for Arm64/ArmHF

### ISSUE THREAD

**Issue by sgofferj** [camptocamp/docker-mapserver#370]
Currently, only images for AMD64 are available from docker hub. Arm-based servers are gaining popularity and the new Ampere Altra servers are almost cheap compared to Intel servers. Also, big public cloud providers are offereing nowadays quite affordable Arm VPS.
For this reasons, plus the possibility to run a test instance on Raspberry Pi, container images for Arm64/ArmHF would be great.

**Comment by sbrunner** [comment]
It looks to be easy :-)
=>  #371

**Comment by sgofferj** [comment]
> It looks to be easy :-) => #371

Great :+1: . Would you consider that also for your mapcache image? I would open a ticket there but the repo is archived...

**Comment by sgofferj** [comment]
Thank you!!! :partying_face:
