### ISSUE TITLE
Publishing docker images for different architectures under the same label

### ISSUE THREAD

**Issue by tfr42** [camptocamp/docker-mapserver#406]
Currenlty the images of [camptocamp/mapserver](https://hub.docker.com/r/camptocamp/mapserver) for other os/architectures are pushed with a different tag like `8.0-arm64` to docker hub. 

To align the deployment of mapserver container in different environments with different os/architectures it would be very helpful to have images for different architectures under the same tag such as it is done for the [multi-platform images](https://docs.docker.com/build/building/multi-platform/) of Apache httpd in https://hub.docker.com/_/httpd/tags.

**Comment by sbrunner** [comment]
This is not possible for us because we separate the building and the publishing, and docker will do them in one command (not separable :-( )

**Comment by tfr42** [comment]
OK, thanks for the quick reply.
