### ISSUE TITLE
Running MapServer container in Rootless mode 

### ISSUE THREAD

**Issue by lgoltz** [camptocamp/docker-mapserver#422]
Running  the docker image [camptocamp/mapserver:8.0](https://hub.docker.com/layers/camptocamp/mapserver/8.0/images/sha256-eda0813bf4f973145a084280716a879afcff4cd5bd7bfa658b3d344155fed189?context=explore) with a non-root user results in a failure: 

```
docker run --rm --user=1001:1001 camptocamp/mapserver:8.0
Switching listen port to 8080
sed: couldn't open temporary file /etc/apache2/sites-available/sedwXRyxa: Permission denied
```

Is it possible to run  [camptocamp/mapserver:8.0](https://hub.docker.com/layers/camptocamp/mapserver/8.0/images/sha256-eda0813bf4f973145a084280716a879afcff4cd5bd7bfa658b3d344155fed189?context=explore) rootless?

**Comment by sbrunner** [comment]
It is strange that a file will be written here, but the group should be 0 (root)...

**Comment by danduk82** [comment]
@lgoltz this should be fixed, a feedback would be much appreciated :)
