### ISSUE TITLE
Regression: mapserver:8.0 docker image does not render Capabilites with additional path anymore

### ISSUE THREAD

**Issue by danduk82** [camptocamp/docker-mapserver#549]
When using `camptocamp/mapserver:8.0` behind  a proxy, the templated URL is no more valid. 
Before for a `GetCapabilties` on `https://some-server.com/custom/` the templated capabitlites URLs would have been generated as such 
```xml
<Get><OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://some-server.com/custom/?"/></Get>
```
but since a few weeks this is broken and it returns
```xml
<Get><OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://some-server.com/?"/></Get>
```
without the `/custom/` part of the URL

this is broken now for a few clients.

**Comment by danduk82** [comment]
I suspect (this commit)[https://github.com/camptocamp/docker-mapserver/commit/3a012131e2d9a16cc3394d9781b0e1edcbc50f4f] to be the culprit

**Comment by danduk82** [comment]
ping @maltaesousa  as you are the author ;) what do you think?

**Comment by sbrunner** [comment]
This feature is probably incompatible with the landing page :-(

**Comment by maltaesousa** [comment]
I don't know what is "templated capabilities". We have a proxy in front of mapserver:8.0 container and setting "ows_onlineresource" accordingly with the final URL works:
https://sitn.ne.ch/services/wms?SERVICE=WMS&REQUEST=GetCapabilities

**Comment by danduk82** [comment]
When I say "templated capabilites" I meant "rendered capabilities" i.e. the response of GetCapablities indeed. I was a bit tired yesterday...
I don't know where the regression is, but I tried with an older image that was laying on my laptop and the issue was fixed. So I'll have to go back in time a bit I guess until I see where the problem is...

**Comment by danduk82** [comment]
After some more debugging, I don't get how it is working on SITN. When trying with a more complex path, on an older image if I GET this:

```
http://some-host.com/coucou/wms/?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
```

I get a full Capabilities file with

```xml
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://some-host/coucou/wms/?"/>
```

but with the new image I get an error:

```
msCGILoadMap(): Web application error. CGI variable "map" fails to validate.
```

I probably have to revert your commit @maltaesousa  , I will get back to you to see how to have a proper ogcapi service, that is also compatible with normal old behavior.

**Comment by sbrunner** [comment]
This looks like hackish :-(, I'm afraid that:
- we lost some case then we add one by on the missing path in the list
- the user except that all cases are working, but we will get too many corner cases
At first look, we should abandon the feature that the server works on all the path and dynamically generate this file for a set of path with an option to support the old case without ogcapi...

In other words, we should be sure that we get something relay robust.

**Comment by sbrunner** [comment]
Why not something like:
```
ScriptAliasMatch "^/${BASE_PATH}(.*)" /usr/local/bin/mapserv_wrapper/$1
```

Then with the value:
 - ``: it's working for OGC API
 - `.*` it's working as the old way
 - `my_path/` everything is working on the subpath `my_path`

**Comment by danduk82** [comment]
Hello @maltaesousa , I will do a PR with the proposition of @sbrunner . I will also add a couple of tests. I will be happy if you could test it on the ogcapi when I push it. (I will already push it with only the functional part, not yet the tests maybe)

**Comment by danduk82** [comment]
@maltaesousa  [here is the PR](https://github.com/camptocamp/docker-mapserver/pull/550).  Can you please test it and validate that it works with your ogcapi setup? You will have to add the `MAPSERVER_BASE_PATH` environment variable according to your setup.

**Comment by danduk82** [comment]
PR and backport done. I close the issue. 
If there is something more, please open an new issue.
