### ISSUE TITLE
mapserver error logging

### ISSUE THREAD

**Issue by pvgenuchten** [camptocamp/docker-mapserver#564]
can you provide some guidance on how to achieve optimal logging setup for mapserver docker?

Desired behaviour: 
- a single environment variable to set logging to DEBUG or PROD
- PROD includes any error messages returned by mapserver binary to docker logs (i always mixup STDOUT/STDERR for ms_errorfile)
- DEBUG setting provides access logs as well as error logs

I assume it's a combination of finetuning [ms_errorfile](https://mapserver.org/optimization/debugging.html) (i'm always confused with STDOUT/STDERR for ms_errorfile) and apache logging options?

**Comment by sbrunner** [comment]
In my environment I just use the `MS_DEBUGLEVEL`, the logs are output by default to the stdout, the `MS_ERRORFILE` should not set in the MapFile...

**Comment by pvgenuchten** [comment]
correct, setting ms_errorfile=stderr and ms_errorfile=5 gives nice result
