### ISSUE TITLE
Failed to fetch package

### ISSUE THREAD

**Issue by leader80** [camptocamp/docker-mapserver#6]
Hi,

I'm trying to run your docker image but is complaining about some URL resolve:

Err http://security.debian.org jessie/updates InRelease
  
Err http://http.debian.net jessie-backports InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://http.debian.net jessie-backports Release.gpg
  Could not resolve 'http.debian.net'
Err http://httpredir.debian.org jessie InRelease
  
Err http://httpredir.debian.org jessie-updates InRelease
  
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Reading package lists...
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://http.debian.net/debian/dists/jessie-backports/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://http.debian.net/debian/dists/jessie-backports/Release.gpg  Could not resolve 'http.debian.net'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package apache2
E: Unable to locate package cgi-mapserver
E: Unable to locate package libapache2-mod-fcgid
E: Unable to locate package curl

Thanks for any tip
Cheer
G.

**Comment by pvalsecc** [comment]
Your are failing to **build** the image. Why do you want to build it? You can get it from Docker Hub.

I guess you have networking issues from your docker containers.
Try that:
```
docker run -ti --rm debian:jessie ping -c 3 security.debian.org
```

**Comment by leader80** [comment]
yes, it's not working :-1: 

ping: unknown host

Thanks
G.
