### ISSUE TITLE
Can't start container after kill/crash

### ISSUE THREAD

**Issue by Toilal** [camptocamp/docker-mapserver#8]
When the container is killed, it's not possible to start it again because of the apache lock file beeing present. Is it possible to disable this "feature" ?

Step to reproduce:

```
$ docker run --name mapserver-lock-test -d camptocamp/mapserver
$ docker kill mapserver-lock-test
$ docker start mapserver-lock-test
$ docker logs --tail=1 mapserver-lock-test 
```
This displays "httpd (pid 1) already running"

```
$ docker ps
```
mapserver-lock-test container is not running.

**Comment by pvalsecc** [comment]
Indeed... but, just out of curiosity, why do you kill your container instead of stopping it?

**Comment by Toilal** [comment]
I don't kill it on purpose, but it may be killed if computer crash or
anything else.

Le 6 janv. 2017 7:37 AM, "Patrick Valsecchi" <notifications@github.com> a
écrit :

**Comment by pvalsecc** [comment]
OK, all the images should be fixed, now.
Thanks @Toilal for this bug report with steps to reproduce and all.

**Comment by Toilal** [comment]
Thanks ! I just tested after pulling the new image, and it works :+1:
