### ISSUE TITLE
Utilisation d'un Alias plus standard pour l'accès au script mapserv

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/docker-mapserver#9]
Peut on définir un alias plus standard et ne pas utiliser le nom du script dans l'url ?

https://github.com/camptocamp/docker-mapserver/blob/master/etc/apache2/conf-enabled/mapserver.conf#L4

Le problème est que les projets GeoMapFish bloque les url qui contiennent la chaîne "mapserv".

Proposition : utiliser "ows"

**Comment by yjacolin** [comment]
Qu'en pensez vous @sbrunner et @pvalsecc ?

**Comment by sbrunner** [comment]
We should simply remove this line :-)

**Comment by yjacolin** [comment]
and manage the path to the service at the load balancing side?

**Comment by yjacolin** [comment]
@sbrunner an use case to explain my issue: we have 2 containers (mapcache and mapserver), we should not use mapserv string in the url AND user should be able to use mapcache or mapserver services. Patrick said "The LB doesn't do any query rewrite and the mapserver doesn't respond to the /ows URL."

How can we use such container without mapserv string in the url and with several other services?

Example with ECA:
* http://bdbh.eca-vaud.ch/mapcache?REQUEST=GetCapabilities
* http://bdbh.eca-vaud.ch/mapserv?REQUEST=GetCapabilities

**Comment by yjacolin** [comment]
See https://github.com/camptocamp/eca_webservice/pull/20 also

**Comment by pvalsecc** [comment]
We could use ScriptAliasMatch to match everything. This container is doing only that anyway. Would that be OK for everybody?

**Comment by yjacolin** [comment]
yes, looks good to me and let the user of LB to chose the best path to use in regards of his projects.
