### ISSUE TITLE
Add openlayers.js file to Docker image

### ISSUE THREAD

**Issue by pvgenuchten** [camptocamp/docker-mapserver#908]
the openlayers.js file is no longer at mapserver.org

http://www.mapserver.org/lib/OpenLayers-ms60.js

the file is missing if you make a maprequest with format=applicaton/openlayers as described in:

https://mapserver.org/development/rfc/ms-rfc-63.html

--- 

comment from Seth:

I'm not sure the cut-down MapServer OpenLayers 2 file is still available anywhere to download.

You can put a copy of the full OpenLayers 2 file on your web server, and then update the MS_OPENLAYERS_JS_URL setting to point to this.This can be set in the new MapServer CONFIG file in the ENV section.
You could also try pointing to a version on a CDN e.g

CONFIG
  ENV
        MS_OPENLAYERS_JS_URL "https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.12/OpenLayers.js"

**Comment by sbrunner** [comment]
Why not just set MS_OPENLAYERS_JS_URL to https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.12/OpenLayers.js in the image?

**Comment by pvgenuchten** [comment]
we noticed that the cloudflare 2.12 js does not work on some of our maps, which are in a non 4326 projection, the older openlayers file actually works fine, we recovered it from archive.org. 

i'm discussin with Seth ohw we can update to a newer js

ok to close, just wanted to flag this, if other people hit this issue
